#!/usr/bin/env python3
"""
Post generated LinkedIn posts to LinkedIn via Zernio API with multimedia support.
Reads from posts_with_images.json and posts each one with image attachments.

Usage:
    python3 post_to_linkedin_zernio.py

Requirements:
    - posts_with_images.json (generated by attach_images_to_posts.py)
    - ZERNIO_API_KEY and ZERNIO_BASE_URL in .env
"""

import os
import json
import datetime
import requests
import re
from dotenv import load_dotenv

load_dotenv()

# Zernio Configuration
ZERNIO_API_KEY = os.getenv("ZERNIO_API_KEY")
ZERNIO_BASE_URL = os.getenv("ZERNIO_BASE_URL", "https://zernio.com/api/v1")
LINKEDIN_ACCOUNT_ID = os.getenv("LINKEDIN_ACCOUNT_ID")
ZERNIO_ENDPOINT = f"{ZERNIO_BASE_URL}/posts"

if not ZERNIO_API_KEY:
    raise ValueError("ZERNIO_API_KEY not set in .env file")
if not LINKEDIN_ACCOUNT_ID:
    raise ValueError("LINKEDIN_ACCOUNT_ID not set in .env file")

# ============================================================================
# Extract Posts from File with Images
# ============================================================================

def extract_posts_from_file():
    """
    Extract posts with images from multimedia JSON file.
    Falls back to text file if JSON not found.
    """
    today = datetime.date.today()
    
    # Try to load from posts_with_images.json (has images)
    json_file = f"output/posts_{today.strftime('%Y%m%d')}/posts/posts_with_images.json"
    if os.path.exists(json_file):
        print(f"📖 Reading posts with images from: {json_file}")
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                posts_data = json.load(f)
            
            posts = []
            for post in posts_data:
                posts.append({
                    "stream": post.get("stream"),
                    "type": post.get("type", "Text Post"),
                    "content": post.get("content", ""),
                    "image_url": post.get("image_url"),  # ✨ NEW: Image URL
                    "source": post.get("source", "")
                })
            return posts
        except Exception as e:
            print(f"⚠️  Error reading JSON posts: {e}")
    
    # Fallback: Read from text file (no images)
    text_file = f"linkedin_posts_{today.strftime('%Y%m%d')}.txt"
    if os.path.exists(text_file):
        print(f"⚠️  posts_with_images.json not found, falling back to text file")
        print(f"📖 Reading posts from: {text_file}")
        
        with open(text_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Parse posts using stream markers
    stream_pattern = r'==+\s*STREAM (\d+) — (.+?)\s*==+(.+?)(?=={60}|$)'
    matches = re.findall(stream_pattern, content, re.DOTALL)
    
    posts = []
    for stream_num, post_type, post_content in matches:
        # Clean up post text
        post_text = re.sub(r'\nSource:.*', '', post_content.strip())
        
        posts.append({
            "stream": int(stream_num),
            "type": post_type.strip(),
            "content": post_text,
            "text": post_text  # Zernio expects 'text' field
        })
    
    print(f"✓ Extracted {len(posts)} posts")
    return posts

# ============================================================================
# Post to LinkedIn via Zernio
# ============================================================================

def post_to_linkedin(post_text, post_type, image_url=None, schedule_hour=None):
    """
    Post a single post to LinkedIn via Zernio API with optional image attachment.
    
    Args:
        post_text: Content to post
        post_type: Type of post (News, Tips, Carousel, etc.)
        image_url: URL of image to attach (optional)
        schedule_hour: Hour to schedule (0-23). None = post now
                      8 = 8 AM, 16 = 4 PM
    """
    
    headers = {
        "Authorization": f"Bearer {ZERNIO_API_KEY}",
        "Content-Type": "application/json",
        "User-Agent": "Daily LinkedIn Posts Pipeline"
    }
    
    # Build platform config with or without scheduling
    platform_config = {
        "platform": "linkedin",
        "accountId": LINKEDIN_ACCOUNT_ID,
    }
    
    # Add scheduling if specified
    if schedule_hour is not None:
        # Calculate scheduled time for today
        today = datetime.date.today()
        scheduled_time = datetime.datetime.combine(
            today, 
            datetime.time(schedule_hour, 0, 0)
        )
        # Convert to ISO format (UTC)
        platform_config["scheduledFor"] = scheduled_time.isoformat() + "Z"
        platform_config["publishNow"] = False
        publish_status = f"scheduled for {schedule_hour}:00"
    else:
        platform_config["publishNow"] = True
        publish_status = "posting now"
    
    # Zernio API format with platforms array
    payload = {
        "content": post_text,
        "platforms": [platform_config]
    }
    
    # ✨ NEW: Add image URL if provided
    if image_url:
        payload["media"] = [{
            "type": "image",
            "url": image_url
        }]
        print(f"  📸 Image attached: {image_url}")
    
    try:
        print(f"\n📤 Posting to LinkedIn ({post_type})...")
        print(f"   Status: {publish_status}")
        
        response = requests.post(ZERNIO_ENDPOINT, headers=headers, json=payload)
        response.raise_for_status()
        
        result = response.json()
        
        # Check for successful response
        if "post" in result and "_id" in result["post"]:
            post_id = result["post"]["_id"]
            scheduled_for = result.get("post", {}).get("scheduledFor", "")
            print(f"✅ Posted successfully! ID: {post_id}")
            if scheduled_for:
                print(f"   Scheduled for: {scheduled_for}")
            return {
                "success": True,
                "post_id": post_id,
                "type": post_type,
                "scheduled_for": scheduled_for,
                "has_image": bool(image_url),  # ✨ NEW: Track if image attached
                "timestamp": datetime.datetime.now().isoformat()
            }
        else:
            print(f"✅ Posted! Response: {result}")
            return {
                "success": True,
                "response": result,
                "type": post_type,
                "has_image": bool(image_url),  # ✨ NEW: Track if image attached
                "timestamp": datetime.datetime.now().isoformat()
            }
    
    except requests.exceptions.RequestException as e:
        print(f"❌ Error posting: {e}")
        if hasattr(e, 'response') and e.response is not None:
            try:
                error_detail = e.response.json()
                print(f"   Error details: {error_detail}")
            except:
                print(f"   Response text: {e.response.text}")
        return {
            "success": False,
            "error": str(e),
            "type": post_type,
            "has_image": bool(image_url),  # ✨ NEW: Track if image was attempted
            "timestamp": datetime.datetime.now().isoformat()
        }

# ============================================================================
# Main
# ============================================================================

def main():
    print("=" * 60)
    print("Posting to LinkedIn via Zernio (with multimedia + scheduling)")
    print("=" * 60)
    print()
    
    # Extract posts
    posts = extract_posts_from_file()
    
    if not posts:
        print("❌ No posts to post")
        return
    
    # Show multimedia info
    posts_with_images = sum(1 for p in posts if p.get("image_url"))
    print(f"✅ Found {len(posts)} posts ({posts_with_images} with images)")
    print()
    
    # Schedule times: 8 AM and 4 PM
    schedule_times = [8, 16]  # 8 AM, 4 PM
    
    # Post each one with scheduled time and image (if available)
    results = []
    for i, post in enumerate(posts):
        schedule_hour = schedule_times[i] if i < len(schedule_times) else None
        image_url = post.get("image_url")  # ✨ NEW: Get image URL from post
        result = post_to_linkedin(
            post["content"],  # Changed from "text" to "content"
            post["type"], 
            image_url=image_url,  # ✨ NEW: Pass image URL
            schedule_hour=schedule_hour
        )
        results.append(result)
    
    # Summary
    print()
    print("=" * 60)
    print("📊 LinkedIn Posting Summary")
    print("=" * 60)
    
    successful = sum(1 for r in results if r["success"])
    failed = len(results) - successful
    
    print(f"✅ Scheduled/Posted: {successful}/{len(results)}")
    if failed > 0:
        print(f"❌ Failed: {failed}/{len(results)}")
    
    print("\n📅 Schedule:")
    for i, result in enumerate(results):
        if result["success"]:
            scheduled = result.get("scheduled_for", "Now")
            post_type = result.get("type", "Unknown")
            has_image = " 📸" if result.get("has_image") else ""
            print(f"   Post {i+1} ({post_type}){has_image}: {scheduled}")
    
    # Save posting log
    log_file = f"linkedin_posting_log_{datetime.date.today().strftime('%Y%m%d')}.json"
    with open(log_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    print(f"\n📝 Posting log saved: {log_file}")
    
    if successful == len(results):
        print("\n✅ All posts scheduled successfully!")
    else:
        print(f"\n⚠️  {failed} posts failed - check log for details")

if __name__ == "__main__":
    main()
