#!/usr/bin/env python3
"""
Post generated LinkedIn posts to LinkedIn via Zernio API.
Reads from linkedin_posts_YYYYMMDD.txt and posts each one.

Usage:
    python3 post_to_linkedin_zernio.py

Requirements:
    - linkedin_posts_YYYYMMDD.txt (generated by generate_posts_2post_model.py)
    - ZERNIO_API_KEY and ZERNIO_BASE_URL in .env
"""

import os
import json
import datetime
import requests
import re
from dotenv import load_dotenv

load_dotenv()

# Zernio Configuration
ZERNIO_API_KEY = os.getenv("ZERNIO_API_KEY")
ZERNIO_BASE_URL = os.getenv("ZERNIO_BASE_URL", "https://zernio.com/api/v1")
LINKEDIN_ACCOUNT_ID = os.getenv("LINKEDIN_ACCOUNT_ID")
ZERNIO_ENDPOINT = f"{ZERNIO_BASE_URL}/posts"

if not ZERNIO_API_KEY:
    raise ValueError("ZERNIO_API_KEY not set in .env file")
if not LINKEDIN_ACCOUNT_ID:
    raise ValueError("LINKEDIN_ACCOUNT_ID not set in .env file")

# ============================================================================
# Extract Posts from File
# ============================================================================

def extract_posts_from_file():
    """Extract posts from daily posts file."""
    today = datetime.date.today()
    posts_file = f"linkedin_posts_{today.strftime('%Y%m%d')}.txt"
    
    if not os.path.exists(posts_file):
        print(f"❌ Posts file not found: {posts_file}")
        print("   Run generate_posts_2post_model.py first")
        return []
    
    print(f"📖 Reading posts from: {posts_file}")
    
    with open(posts_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Parse posts using stream markers
    stream_pattern = r'==+\s*STREAM (\d+) — (.+?)\s*==+(.+?)(?=={60}|$)'
    matches = re.findall(stream_pattern, content, re.DOTALL)
    
    posts = []
    for stream_num, post_type, post_content in matches:
        # Clean up post text
        post_text = re.sub(r'\nSource:.*', '', post_content.strip())
        
        posts.append({
            "stream": int(stream_num),
            "type": post_type.strip(),
            "content": post_text,
            "text": post_text  # Zernio expects 'text' field
        })
    
    print(f"✓ Extracted {len(posts)} posts")
    return posts

# ============================================================================
# Post to LinkedIn via Zernio
# ============================================================================

def post_to_linkedin(post_text, post_type):
    """Post a single post to LinkedIn via Zernio API."""
    
    headers = {
        "Authorization": f"Bearer {ZERNIO_API_KEY}",
        "Content-Type": "application/json",
        "User-Agent": "Daily LinkedIn Posts Pipeline"
    }
    
    # Zernio API format with platforms array
    payload = {
        "content": post_text,
        "platforms": [
            {
                "platform": "linkedin",
                "accountId": LINKEDIN_ACCOUNT_ID,
                "publishNow": True
            }
        ]
    }
    
    try:
        print(f"\n📤 Posting to LinkedIn ({post_type})...")
        
        response = requests.post(ZERNIO_ENDPOINT, headers=headers, json=payload)
        response.raise_for_status()
        
        result = response.json()
        
        # Check for successful response
        if "id" in result or "_id" in result:
            post_id = result.get("id") or result.get("_id")
            print(f"✅ Posted successfully! ID: {post_id}")
            return {
                "success": True,
                "post_id": post_id,
                "type": post_type,
                "timestamp": datetime.datetime.now().isoformat()
            }
        else:
            print(f"✅ Posted! Response: {result}")
            return {
                "success": True,
                "response": result,
                "type": post_type,
                "timestamp": datetime.datetime.now().isoformat()
            }
    
    except requests.exceptions.RequestException as e:
        print(f"❌ Error posting: {e}")
        if hasattr(e, 'response') and e.response is not None:
            try:
                error_detail = e.response.json()
                print(f"   Error details: {error_detail}")
            except:
                print(f"   Response text: {e.response.text}")
        return {
            "success": False,
            "error": str(e),
            "type": post_type,
            "timestamp": datetime.datetime.now().isoformat()
        }

# ============================================================================
# Main
# ============================================================================

def main():
    print("=" * 60)
    print("Posting to LinkedIn via Zernio")
    print("=" * 60)
    print()
    
    # Extract posts
    posts = extract_posts_from_file()
    
    if not posts:
        print("❌ No posts to post")
        return
    
    # Post each one
    results = []
    for post in posts:
        result = post_to_linkedin(post["text"], post["type"])
        results.append(result)
    
    # Summary
    print()
    print("=" * 60)
    print("📊 LinkedIn Posting Summary")
    print("=" * 60)
    
    successful = sum(1 for r in results if r["success"])
    failed = len(results) - successful
    
    print(f"✅ Posted: {successful}/{len(results)}")
    if failed > 0:
        print(f"❌ Failed: {failed}/{len(results)}")
    
    # Save posting log
    log_file = f"linkedin_posting_log_{datetime.date.today().strftime('%Y%m%d')}.json"
    with open(log_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    print(f"\n📝 Posting log saved: {log_file}")
    
    if successful == len(results):
        print("\n✅ All posts posted successfully!")
    else:
        print(f"\n⚠️  {failed} posts failed - check log for details")

if __name__ == "__main__":
    main()
